# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: [ '8' ] # , '11', '13', '15' ]
    name: Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Split branch name
        run: echo "BRANCH_NAME=${{ github.head_ref }}" | sed -e s/\\//\-/g >> $GITHUB_ENV
      - name: versioning
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}-${increment}"
          namespace: ${{ env.BRANCH_NAME }}
          bump_each_commit: false
        id: versioning
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          GITHUB_CI_TOKEN: ${{ secrets.CI_TOKEN }}
          GITHUB_CI_ACTOR: ${{ secrets.CI_USER }}
      - name: Publish package
        run: ./gradlew -Pversion=${{steps.versioning.outputs.version}} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_CI_TOKEN: ${{ secrets.CI_TOKEN }}
          GITHUB_CI_ACTOR: ${{ secrets.CI_USER }}


